backend:
  name: github
  repo: vml-kkedrovsky/kc-covid-response
  branch: master

media_folder: 'static/uploads'
public_folder: '/uploads'

collections:
  - name: 'faq'
    label: 'FAQ'
    summary: {{ order }} - {{ question }}
    folder: 'content/faqs'
    create: true
    identifier_field: 'question'
    fields:
      - { label: 'Order', name: 'order', widget: 'number', valueType: 'int' }
      - { label: 'Question', name: 'question', widget: 'string' }
      - { label: 'Answer', name: 'body', widget: 'markdown' }
    sortableFields: ['order', 'question']
