backend:
  name: git-gateway
  branch: master
collections:
  - name: 'faq'
    label: 'FAQ'
    folder: 'content/faqs'
    create: true
    identifier_field: 'question'
    fields:
      - { label: 'Question', name: 'question', widget: 'string' }
      - { label: 'Answer', name: 'answer', widget: 'markdown' }
