backend:
  name: github
  repo: karlkedrovsky/kc-covid-response
  branch: master

media_folder: 'static/uploads'
public_folder: '/uploads'

collections:
  - name: 'faq'
    label: 'FAQ'
    folder: 'content/faqs'
    create: true
    identifier_field: 'question'
    fields:
      - { label: 'Question', name: 'question', widget: 'string' }
      - { label: 'Answer', name: 'body', widget: 'markdown' }
